### ISSUE TITLE
Fehlermeldung bei Passworteingabe

### ISSUE THREAD

**Issue by intradesign** [eikona-media/contao-password-policy#1]
Hallo,
ich habe das Password-Policy-Bundle mal testweise installiert und das Passwort-Rezept auf 16-32 Zeichen mit je einem Sonderzeichen, Groß- und Kleinbuchstaben und einer Zahl gesetzt.

Wenn ich nun ein Passwort festlege (in der Benutzerverwaltung) erhalte ich den Hinweis, dass das eingegebene Passwort mindestens 16 Zeichen enthalten soll, wenn ich ein kürzeres eingebe.

Wenn ich ein korrekt passendes eingebe, erhalte ich folgende Meldung, die direkt unter dem Passwort-Feld angezeigt wird:

> The "eikona_media.contao.password_policy.policy_service" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

<img width="805" alt="benutzer benutzer id 5 bearbeiten - contao open source cms 2019-02-20 14-08-29" src="https://user-images.githubusercontent.com/21263208/53093918-02dcf380-3519-11e9-9482-86b4e700722b.png">

Als Passwort habe ich folgendes gewählt: (z3YC6JJ@UWRvYfK

Nach dem Speichern (das nicht funktioniert) wird das Passwort auf die 5 Zeichen gekürzt dargestellt. Erneutes Speichern gibt den Hinweis, dass das eingegebene PW zu kurz ist.

Contao läuft in Versioin 4.7 mit PHP 7.2.

Habe ich etwas falsch gemacht oder gibt es einen Fehler?

Danke und viele Grüße
Timo

**Comment by rabauss** [comment]
Yes, there was obviously an error in our service definition.
can you please check again with version 1.0.1?

Fixed by 633bb78a3e42b04d7e8e3fbd4c36db9c6677faa0

**Comment by devtty80** [comment]
Can confirm fix on fresh Contao 4.7 install.
Thanks @rabauss

**Comment by devtty80** [comment]
Can also confirm for fresh Contao 4.4 LTS install.
