### ISSUE TITLE
No login possible

### ISSUE THREAD

**Issue by raukm** [eikona-media/contao-password-policy#2]
Wenn i use the contao registration module for frontenduser the validation worked. But after the activation they can’t login.
Everytime there is the report: „Anmeldung fehlgeschlagen (Benutzernamen und Passwörter unterscheiden zwischen Groß- und Kleinschreibung)!“

I checked the entry in the database. In the field password is only the value „1“ for every member who registered after the implementation of the module.
I think that is the problem that the member can’t login anymore

Tested in Contao 4.4.47

**Comment by devtty80** [comment]
Hi, thanks for reporting.
Seems to me that here (without testing yet), for some reason the output of the validateMemberPassword method (boolean - true == 1) is taken for the password value, instead of only validating and throwing an exception in case of failure.

**Comment by rabauss** [comment]
Should be fixed ;-)
